=== AMP2563/ejercicios_xml_2/ejercicio_2.dtd
<!ELEMENT agenda (contacto+)>
<!ELEMENT contacto (nombre, telefono, email?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST contacto tipo (personal | profesional) "personal">

=== AMP2563/ejercicios_xml_2/ejercicio_2.xml
<?xml version="1.0"?>

<!DOCTYPE agenda SYSTEM "ejercicio_2.dtd">
<agenda>
  <contacto tipo="profesional">
    <nombre>Ana López</nombre>
    <telefono>123456789</telefono>
    
  </contacto>
  <contacto tipo="profesional">
    <nombre>Ana López</nombre>
    <telefono>123456789</telefono>
    <email>ana@empresa.com</email>
  </contacto>
</agenda>
